# Generated by Django 4.0.3 on 2023-11-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovnis_api', '0004_sighting_image_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='description',
            field=models.CharField(default='', max_length=400),
        ),
    ]
