# Generated by Django 4.0.3 on 2023-11-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovnis_api', '0005_sighting_title_alter_sighting_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='image',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
